### ISSUE TITLE
Consider putting bcf information into the config.yaml rather than the harder to read TSV

### ISSUE THREAD

**Issue by eriqande** [eriqande/mega-post-bcf-exploratory-snakeflows#4]
It would go something like this:

```yaml
bcf_list:
    id: TEST-Biallelic-SNPS-5-fish-maf-0.1
    path:  .test/bcf/test.bcf
    sample_subset_path: .test/config/sample_subsets/fish5.txt
    bcftools_opts:  -v snps -m 2 -M 2 -i 
    scaff_group_path: .test/bcf/test.bcf.scaff_groups.tsv
```
I think that would be a lot easier to look at and modify, etc.
